### ISSUE TITLE
Reorganizar modelos intermediários de licenciamento em staging

### ISSUE THREAD

**Issue by fernandascovino** [prefeitura-rio/queries-rj-smtr#245]
Nova estrutura:

- `rj-smtr-staging.[datset_id]_staging.[table_id]`: tabela nativa GCS
- `rj-smtr.[dataset_id]_staging.[table_id]`: tabela desaninhada 
- `rj-smtr.[datatset_id]`: tabela final

**Comment by pixuimpou** [comment]
Finalizando os testes hoje, expectativa de criar o PR hoje
