### ISSUE TITLE
Refatorar tabela de parâmetros do subsídio

### ISSUE THREAD

**Issue by fernandascovino** [prefeitura-rio/queries-rj-smtr#251]
- Revisar e testar nova estrutura: https://docs.google.com/spreadsheets/d/1GNgdLkRdpTo3G40XEW3YRz6WtlYAMEGqPfFbXUyMnL0/edit#gid=125724517
- Corrigir uso no Encontro de contas: https://github.com/prefeitura-rio/queries-rj-smtr/pull/243

**Comment by eng-rodrigocunha** [comment]
Tabela será refatorada no âmbito do https://github.com/prefeitura-rio/pipelines_rj_smtr/pull/121
