### ISSUE TITLE
Incluir apuração por faixa horária do subsídio

### ISSUE THREAD

**Issue by pixuimpou** [prefeitura-rio/queries-rj-smtr#335]

**Comment by pixuimpou** [comment]
Esperando sair ordem de serviço no novo formato

**Comment by akaBotelho** [comment]
## Ações complementares
- Label para tabelas usadas em dashboard
- ordem_servico precisará ter sua estrutura alterada para nova primary_key = ["servico", "tipo_os", "faixa_horaria_inicio","faixa_horaria_fim"]

**Comment by pixuimpou** [comment]
Novo modelo de ordem de serviço enviado

**Comment by pixuimpou** [comment]
Aguardando SUBP enviar novo anexo da ordem de serviço

**Comment by eng-rodrigocunha** [comment]
Incluir nova tabela de pré-apuração: `view` com os agrupamentos das viagens realizadas x planejado para consumo interno pela SUBP/CGR. Tabela não deve ficar pública. Avaliar que seja incluída no dataset `monitoramento_dashboard`.
